### PR TITLE
Adds PL translation

### LINKED ISSUE #282: Polish translation
How can I start translating the core module to Polish language? Just open a PR?

### PR DESCRIPTION
**Pull request by lukaszlenart**
Closes #282

### CODE REVIEW

**Comment by pwatson100** [comment]
Hi Lucas,   Have you pushed the correct file?  The only items in Polish are the text that is used in the drop-down when an Actor is created. 

Paul.

**Comment by lukaszlenart** [comment]
I just started, the PR is draft and I will let you know once ready

**Comment by pwatson100** [comment]
Ok.

**Comment by lukaszlenart** [comment]
It's done, yet I asked our friends to take a look as I probably made some mistakes :D

**Comment by pwatson100** [comment]
Lukasz, 
Thank you for doing this.  I have mergd it into my latest development branch (post-v12) and have noticed that as some of the words are longer than their Engklish counterparts its effecting the sheet formatting.  
I was wondering if some of the could be abbreviated? 
You should be able to download and install the post-v12 version to see what I mean.

**Comment by pwatson100** [comment]
Ah sorry , it cant be installed that way.  
You need to switch to the branch and under <>Code tab download the zip file then create an alienrpg directory under system and unzip the file into it.

**Comment by lukaszlenart** [comment]
I was able to review the package and notice some issues, I will prepare another PR addressing those

**Pull request merged**
