### PR TITLE
New Branch for Pull Request - SubmittoMain1

### PR DESCRIPTION
**Pull request by David-Zvekic**
Hi Paul.

This pull has all the changes from the earlier one.  Plus fixes a firefox/DicesoNice Stressroll issue. Also synthetics can click the word "No Stress" and create a fake panic roll. (It never rolls above 6, but it might slightly make it easier to fake being human).

You should have the ability to make modifications to SubmitToMain1, and I wont make any more mods to this branch.

Git hub will let you go through a conflict resolution process now because you should have the ability to modify SubmittoMain1.  And commit changes back into SubmittoMain1.

all your conflict resolution is pushed back into SubmitToMain1 -- and when you are happy with everything, then you can click Accept Pull request and it will be exactly how you want it to be because its what you put into the SubmitToMain branch.

Once you update your main alienrpg master branch thats the official version with whatever you want in it.  

Original CHANGES in the PULL REQUEST from prior Pull Request

ENHANCEMENT- cause inventory to automatically calculate ammo weights as per Destroyer of Worlds
(this version is a hack because it is hard coded to search for the word RPG in the class or weapon name.
ideally the Weapon Item would have an ammo weight member in the object itself.) The rule is 0.25 weight per load for all ammo, but 0.5 weight for RPGs.

ENHANCEMENT- slight reorganization on character sheet to show current panic value which is important for people to be able to reference for roleplaying, and make the Personal Agenda box easier to read.

ENHANCEMENT- Make SquareGrid calculate distances using euclidean distance to the nearest cm, rather than using Dungeons and Dragons 5e method. This makes it feel more like science fiction and less like a board game. This could be relatively easily turned into a setting, but there is no good reason not to use euclidean distance since distance calculations are not even part of the Alien game.

BUGFIX -Fix a bug where PUSHing a skill roll gives stress to the selected token rather than the original actor. Also other players could push skill rolls for characters they dont own - but they would take the stress. Now there is 0 dependancy on any tokens. the stress goes to the original actor that made the skill roll.

ENHANCEMENT- - actor.rollAbility(actor, {panicroll:1,mod:0}) should make a panic check, but synthetics could not invoke this. Now synthetics and characters can all make panic checks - synthetics never actually panic, but the result shows up as if they Keep it Together. not letting synthetics check for panic makes it obvious which actors are not human. TODO: modify synthetic sheet to turn 'stress' into a button - synth players can check with a macro however to keep up an illusion.

REFACTOR - removed a 60 lines of unnecessarily duplicated code. When someone rolls panic with modifiers, there is no reason to duplicate the entire code of the panic check, simply get the modifier from a dialog and invode the original actor.rollAbility(actor, {panicroll:1,mod:XXX}) function and pass the modifier rather than XXX.

ENHANCEMENT- when actors become panicked their Token now shows the 'fear.svg' overlay. When they stop being panicked their fear.svg overlay vanishes. This only happens to tokens which are already in play in the current scene. TODO maybe - check the value when dropping a token onto a scene and when changing scenes

BUGFIX - fixed a bug where skill checks were not properly respecting the visibility of rolls. Skill rolls will now be private or whispered to the GM if those settings are selected in the Chat tab.

### CODE REVIEW

**Comment by pwatson100** [comment]
That did the trick.  Those changes look really good.  I just need to do some more testing to make sure none of the official modules break.  
I had to make a slight change as the css textbox change mucked up a few of the other sheets which I have now corrected.   
I have uploaded the changes to the Dave-Zvekic-Enhancements branch if you want to take a look.  
That also has the new Initiative system which is better suited to Alien.
Check out the first draft of the MO/TH/ER Instructions journal entry.  I have received some feedback from my regular play testers which I need to incorporate as well as the modifications you have contributed.

**Comment by pwatson100** [comment]
I forgot to ask are you on Discord?

**Comment by David-Zvekic** [comment]
My discord is DM9290#0073. Send me a friend request.

I've confirmed everything in the David-Zvekic-Enhancements branch works
with all of my worlds and the new MO/TH/ER instructions look amazing!
The clone actor initiative feature works well.   (I was previousy dropping
extra non-visible copes of enemy tokens as placeholders, but this is far
superior).
I also noticed if necessary the GM is free to type decimal initiatives so
when swapping places the GM can ensure the desired initiative order is
preserved.

I've pushed everything into my own master branch on github and anything
else will be based on that.

**Comment by pwatson100** [comment]
Thanks I sent you a friend request.  
One thing I have noticed is when the fear.svg appears it's the big version:
image
was that intended? 
I had a quick run at FVTT 0.8 last night.  Not great and it looks like a fair amount of work just to get the system working properly.  

Thinking about Synthetics the big issue with using the Synthetic sheet for a "Secret Android" is that they will never roll stress dice which is a bit of a give away to the other players.  There is also the point that they will be seen to have higher attributes when the make rolls.   I think the only real solution is for the GM to give the player a character and Syth sheet and let them play using the character sheet until they are exposed roleplaying the effects.

**Pull request merged**
