### PR TITLE
Small bugfix about dice rolls and typos

### PR DESCRIPTION
**Pull request by gerdos**
Dice rolls were not working, I figured this fix, not entirely sure about it now, but it works.

Added small type correction for the word 'success'

### CODE REVIEW

**Comment by pwatson100** [comment]
Hi,  what was the issue with the dice rolls?  I have tested and can't see an issue.  The line in actor.js is supposed to be itemData.attributes.  In the last update I added a modifiers tab to the Itemsheet.  These are defined in the template.json as item.attributes

**Comment by gerdos** [comment]
Hi!

I just freshly installed the system on Foundry, and at the beginning I was able to roll skills, however after a while I was getting this error:

Uncaught (in promise) Error: The dice roll formula undefined + 1ds did not produce a numeric outcome.
    at Roll.evaluate (foundry.js:7665)
    at Roll.roll (foundry.js:7692)
    at Function.yzeRoll (YZEDiceRoller.js:136)
    at HTMLButtonElement.<anonymous> (alienrpg.js:318)

3actor.js:38 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at actor.js:38
    at Array.reduce (<anonymous>)
    at alienrpgActor.getRollData (actor.js:34)
    at alienrpgActor.rollAbility (actor.js:285)
    at alienrpgActorSheet._onRoll (actor-sheet.js:365)
    at HTMLHeadingElement.dispatch (jquery.min.js:2)
    at HTMLHeadingElement.v.handle (jquery.min.js:2)

I am just beginning to understand what happens, but I saw that the itemData object had no 'attributes' value in it.

**Comment by pwatson100** [comment]
That is an odd one.  The error suggests there is no value in that attribute.  But the roll won't happen if the field is blank and if it has 0 or a negative number it rolls but does not display any dice in the chat.  I have been trying to reproduce the error but can't.   Are you able yo repeat the issue and could you describe the steps you take to cause the error please.

**Comment by gerdos** [comment]
I will try to do it tomorrow morning

**Comment by gerdos** [comment]
I hope that this will help:

I created a user for you on my Foundry server: https://daryon.ddns.net/join 
The user is your name user name from here and there is no password. You will have access to a character and you can reproduce the issue with it. I also changed back my "fix", as I guess it does not a real fix for the problem

**Comment by pwatson100** [comment]
Thank you that was very useful.  So there seems to be something wrong with your installation.  None of the Skill-Stunt items or RollTables are there.  

The error we are seeing in actor.js is because there are no items (that I could see).  I will see what I can do to patch this issue.  

 

With respect to the die rolling, I was getting a different error to the one you mentioned.  

actor.js:38 Uncaught (in promise) TypeError: Cannot convert undefined or null to object…..

 

Looking at the chat log it seems the rolls were working a few hours ago??   Have you made any changes to the code?

 

I would suggest the easiest thing to do would be to uninstall and re-install the system (it won’t hurt your World).  

When the system installed for the first time it imports some tables (Panic Table) and items(Skill Stunts) the system needs to work so you should not delete these.  

 

Let me know how you get on.  

Regards,

Paul.

**Comment by gerdos** [comment]
Thanks a lot, I will try to reinstall the system tomorrow! The rolls were working if I apply the fix I pushed herez thats why you saw the rolls. I now see, that this is obviously not a fix, so please disregard that part.

Thanks a lot for the help, I ll get back tomorrow with the results.

**Comment by gerdos** [comment]
I just reinstalled the system, and nothing changed. The mentioned tables are not there, and the rolls are still not working.

I checked the server log as well and it seems to me the installation was successfully without any errors.

**Comment by pwatson100** [comment]
I did a fresh install on my server on "The Forge" and did not have any errors.  
I wonder if there was an issue when the world was created??
Could you try creating a new world and see if that fixes the issue.  
Are you on the Foundry Discord?   It's a lot easier to communicate on there.  
I am going to close this pull request as the issue is not with the areas you have changed.

**Comment by pwatson100** [comment]
I did a fresh install on my server on "The Forge" and did not have any errors.  
I wonder if there was an issue when the world was created??
Could you try creating a new world and see if that fixes the issue.  
Are you on the Foundry Discord?   It's a lot easier to communicate on there.  
I am going to close this pull request as the issue is not with the areas you have changed.

**Comment by gerdos** [comment]
Yeah I am on the Foundry Discord, Daryon@6667

**Comment by gerdos** [comment]
I was also able to replicate the bug on a fresh install. If I create a new world.

When creating a new word, I create a new actor, and I can roll just fine (BTW the tables you mentioned are still not there). I opened up the "Stunt-Skills" compendium and drag and drop "Close Combat" onto the Skills sheet. 

After this the bug happens, and I am not able to roll anything with the error message I posted earlier.

**Pull request closed without merging**
