### PR TITLE
some enhancements and bugfixes for your consideration

### PR DESCRIPTION
**Pull request by David-Zvekic**
List of all changes - these essentially just from the comments so you can identify the files affected by looking at them directly.

If you wish, please feel free to integrate and distribute these changes as per the Apache license. I would appreciate being credited for any contributions you decide to keep in your repository if you dont mind.   

Regards!

CHANGES in the PULL REQUEST

ENHANCEMENT- cause inventory to automatically calculate ammo weights as per Destroyer of Worlds
 (this version is a hack because it is hard coded to search for the word RPG in the class or weapon name.
ideally the Weapon Item would have an ammo weight member in the object itself.) The rule is 0.25 weight per load for all ammo, but 0.5 weight for RPGs.

ENHANCEMENT- slight reorganization on character sheet to show current panic value which is important for people to be able to reference for roleplaying, and make the Personal Agenda box easier to read.

ENHANCEMENT- Make SquareGrid calculate distances using euclidean distance to the nearest cm, rather than using Dungeons and Dragons 5e method. This makes it feel more like science fiction and less like a board game. This could be relatively easily turned into a setting, but there is no good reason not to use euclidean distance since distance calculations are not even part of the Alien game.

BUGFIX -Fix a bug where PUSHing a skill roll gives stress to the selected token rather than the original actor. Also other players could push skill rolls for characters they dont own - but they would take the stress.  Now there is 0 dependancy on any tokens.  the stress goes to the original actor that made the skill roll.

ENHANCEMENT- - actor.rollAbility(actor, {panicroll:1,mod:0}) should make a panic check, but synthetics could not invoke this. Now synthetics and characters can all make panic checks - synthetics never actually panic, but the result shows up as if they Keep it Together. not letting synthetics check for panic makes it obvious which actors are not human. TODO: modify synthetic sheet to turn 'stress' into a button - synth players can check with a macro however to keep up an illusion.

REFACTOR - removed a 60 lines of unnecessarily duplicated code. When someone rolls panic with modifiers, there is no reason to duplicate the entire code of the panic check, simply get the modifier from a dialog and invode the original actor.rollAbility(actor, {panicroll:1,mod:XXX}) function and pass the modifier rather than XXX.

ENHANCEMENT- when actors become panicked their Token now shows the 'fear.svg' overlay. When they stop being panicked their fear.svg overlay vanishes.  This only happens to tokens which are already in play in the current scene.  TODO maybe - check the value when dropping a token onto a scene and when changing scenes

BUGFIX - fixed a bug where skill checks were not properly respecting the visibility of rolls.  Skill rolls will now be private or whispered to the GM if those settings are selected in the Chat tab.

### CODE REVIEW

**Comment by pwatson100** [comment]
Hi David, Thank you for the suggestions/Enhancements.  Much appreciated. Of course I will accredit you for the new features.   I have created a new branch called David-Zvekic-Enhancements from my master branch which had a few updated I had not uploaded so I can do some testing but I am getting a couple of merge conflicts.  I use Sass so don't edit the css file directly.  I have made the changes in the my scss files to incorporate your additions.  The problem I am facing is when I try to resolve the merge conflicts it want's to commit to your master which I am hesitant to do.     FYI.  The official modules are being released next week (please do not share this information :) ) so I may not release these changes till after the go live hence my creating a separate branch I can merge with master later.

**Comment by David-Zvekic** [comment]
hi, P..

Is P an abbreviation for Peter?  Thank you for looking at my suggestions.

I'm excited that official modules are finally being released soon!

I will warn you, for this pull request version - I didn't didn't notice an
issue on Firefox with Dice So Nice when someone makes a panic check.    The
behavior is the same as your mainbranch on Opera and Chrome (except it
honours the roll-privacy choice of the player).  On firefox the panic roll
starts to misbehave if using Dice So Nice. Anyway just a warning - this has
been fixed (subsequent to the pull request), and now my mainbranch renders
the 1D6 roll in 3d for panic rolls on Chrome, Opera and Firefox and no
longer conrtibutes to a hidden exception appearing inside the DiceSoNice JS
space.

I'm running regular Alien games on Foundry for mostly strangers on the
internet. I think it's a good thing to do to help people socially distance
so I feel motivated.  I also run a weekly D&D game on Foundry and we are
all software developers so we are very aware of any technical issues and as
a GM I feel like my players blame me unless I fix them. :)

Thank you for helping to bring alien Roleplaying game to Foundry VTT!  I
will say that it took much work to migrate, but my roll20 Alien environment
now can't hold a candle to what you helped make possible on Foundry.

Cheers!

David Zvekic

**Comment by pwatson100** [comment]
The p. is for Paul (Paul Watson#0965 on Discord).  
It's been a fun experience and I have leaned a lot and there are a few things I would have done differently if I started over.  I am not a professional programmer hence the scrappy code.   But it works most of the time. 
 
I think Firefox is a little more fussy about code and I know some other systems and modules it does not play nice with.  

I still cant work out in Github how to resolve the merge conflicts without the system making changes to your master???

**Comment by David-Zvekic** [comment]
I think the easiest way for you to resolve the conflict is if I give you
access to commit to my branch that I'm sending you a pull request from.

Thus I'm going to create a new branch. send you a new pull request from
THAT branch and give you full ability to commit back into my branch. then
that way github will let you commit the conflict changes into my branch I
sent you.
once you are happy with all that and you've removed all the "conflict
markers" then github will give you the option to accept the pull request
from the changes that you made to that branch.

I wont touch that branch anymore.  And any work I do I will in the
meanwhile I'll just do to my own separate branch.

when you get the new pull request, just cancel the old one.  I'll update
the comments in the new pull request.
If you have already figured out a way to do it with the old pull request
thats fine too.

David

**Comment by pwatson100** [comment]
New pull request received so closing this one.

**Pull request closed without merging**
