### PR TITLE
fix(initiative): missing default initiative

### PR DESCRIPTION
**Pull request by Stefouch**
I have experienced some crashes in the Combat Tracker. Using the debugger, I found that the `game.system.data.initiative` in line 31810 of foundry.js is undefined. In this situation, the Roll class cannot create a roll for the initiative.

### CODE REVIEW

**Comment by pwatson100** [comment]
Happy to merge this but I defined that in alienrpg.js:
  /**
   * Set an initiative formula for the system
   * @type {String}
   */
  CONFIG.Combat.initiative = {
    formula: '1d10',
    decimals: 1,
  };

Does the crash occur all the time or just occasionally?

**Comment by Stefouch** [comment]
After a little investigation, the Combat Tracker crash only occurs with the [Reverse Initiative](https://github.com/wakeand/fvtt-module-reverseinitiativeorder) module.

> The module is almost mandatory for most Year Zero games (including Alien RPG) because:
> - It reverses the initiative order (ascending order, like in the core rules).
> - It allows multiple initiative slots for a single actor: useful for Xenos with 2+ Speed.

Without this fix, the module does not work properly.

Just in case, I've also tested the system with this fix and without the module and it seems to work fine too.

**Comment by pwatson100** [comment]
Thanks for looking into this. Spent all this morning on this.   
I have looked at the other YZE systems and none of them have the intuitive defined in system.json.  I did a quick test with Forbidden Lands and the same error occurs there.  Looking at the Reverse Initiate module the author is actually overwriting the CONFIG.Combat.initiative variable we are setting on our systems:
        await ReverseInitiativeOrder.registerSettings();
        CONFIG.Combat.initiative = {
            formula: null,
            decimals: 0
        };

I have tried the module with D&D5e as well and it produces the same error.  

I have found if I comment out 
CONFIG.Combat.initiative = {
            formula: null,
            decimals: 0
        };
in reverse-initiative-order.js it works properly.   Though it's still throwing an null error on line 76 but the actual Initiative roll no longer throws an error.  
When the combat initializes the combatants initiative is set to null by Foundry.  It looks like the module is trying to read that value which is throwing the null error.

**Comment by Stefouch** [comment]
OK thank you for this investigation. The problem is clearly from the module. Is it possible to link our conversation in a issue request in their git ?

Also, is it possible to still define the `initiative` property in the JSON ?
From what I understand on line 31810 of foundry.js, it's a safe fallback in case `CONFIG.Combat.initiative` is undefined. The system will prioritize the later over the JSON property.

**Comment by pwatson100** [comment]
I don't know of a way to link the issue to his Git.  You would need to raise a new issue there.  
I have no problem with defining it in the JSON as well.  There is no "special" initiative mechanic so it wont break anything.  I will merge the request so it will be in the next release.

**Pull request merged**
